### PR TITLE
feat: add model for a ready index build

### PR DESCRIPTION
**Pull request by buddy326**

### CODE REVIEW

**Review by igboyes — COMMENTED** [review]
Please explain this in the PR comment.

**Comment by buddy326** [comment]
The following request returns a list of latest, ready index builds for all references: 

GET /api/indexes?ready=true 

The builds that are returned are modelled by the IndexReady class added in this PR.

**Review by igboyes — COMMENTED** [review]
Instead of adding more models, I'd like the endpoint to return `IndexMinimal` instead. This will make this PR unnecessary and make the API more consistent.

Sound good?

**Comment by buddy326** [comment]
Okay I get what you mean, so would you like me to modify the endpoint code accordingly and the index builds that are returned from the database should get other fields added onto them right and then converted to a `IndexMinimal` model?

**Comment by igboyes** [comment]
> Okay I get what you mean, so would you like me to modify the endpoint code accordingly and the index builds that are returned from the database should get other fields added onto them right and then converted to a `IndexMinimal` model?

That is correct. The code should already be in the request handler since `IndexMinimal` is returned when `ready` is not included in the URL query.

**Comment by buddy326** [comment]
Sweet I understand, thank you.

**Pull request closed without merging**
